# OrbIQ System Monitoring Configuration

[mqtt]
broker = "localhost"
port = 1883
username = "uname"
password = "password"
keep_alive_secs = 30

[device]
name = "hostname"
hw_version = "1.0"

# Update interval in seconds
update_interval_secs = 30

# Delay between discovery messages in milliseconds
discovery_delay_ms = 200
